version: '3'
services:
  ethereum-client:
    image: ethereum/client-go:v1.13.4
    command:
      - '--state.scheme=path'
      - '--datadir=/execution-data'
      - 'init'
      - '/el-cl-genesis-data/custom_config_data/genesis.json'
    volumes:
      - './execution-data:/execution-data'
      - './config-example:/config'
      - './el-cl-genesis-data:/el-cl-genesis-data'
    tty: true
    stdin_open: true
