version: "3.8"

services:
  ethereum-genesis-generator:
    image: wangyufsn/ethereum-genesis-generator:2.0.4
    command: all
    environment:
      - http_proxy=http://host.docker.internal:7890
      - https_proxy=http://host.docker.internal:7890
      - all_proxy=socks5://host.docker.internal:7890
    volumes:
      - ./el-cl-genesis-data:/data
      - ./config-example:/config
    tty: true
    stdin_open: true
    restart: "no"
    